# ── R Markdown Report Generator ─────────────────────────
# Generates a self-contained HTML report
# Run: Rscript r_scripts/report.R creditcard.csv

args     <- commandArgs(trailingOnly = TRUE)
csv_path <- if (length(args) > 0) args[1] else "creditcard.csv"
csv_path <- normalizePath(csv_path, winslash = "/", mustWork = FALSE)

script_arg <- commandArgs(trailingOnly = FALSE)
script_path <- sub("^--file=", "", script_arg[grep("^--file=", script_arg)][1])
base_dir <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/", mustWork = FALSE)
r_lib <- file.path(base_dir, "r_library")
dir.create(r_lib, recursive = TRUE, showWarnings = FALSE)
.libPaths(c(r_lib, .libPaths()))

pandoc_dir <- file.path(Sys.getenv("LOCALAPPDATA"), "Pandoc")
if (dir.exists(pandoc_dir)) {
  Sys.setenv(RSTUDIO_PANDOC = pandoc_dir)
  Sys.setenv(PATH = paste(pandoc_dir, Sys.getenv("PATH"), sep = .Platform$path.sep))
}

pkgs <- c("rmarkdown", "knitr", "ggplot2", "dplyr", "scales", "kableExtra")
for (p in pkgs) {
  if (!require(p, character.only = TRUE, quietly = TRUE)) {
    install.packages(p, repos = "https://cloud.r-project.org", quiet = TRUE)
    library(p, character.only = TRUE)
  }
}

cat("=== R Markdown Report Generator ===\n")

# Write the .Rmd file dynamically
rmd_content <- sprintf('---
title: "Credit Card Fraud Detection — Analysis Report"
author: "FraudGuard ML System"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: darkly
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.width=8, fig.height=4)
library(ggplot2); library(dplyr); library(scales); library(kableExtra)
df <- read.csv("%s")
df$Class <- as.factor(df$Class)
```

## Dataset Overview

```{r}
summary_df <- data.frame(
  Metric = c("Total Rows","Fraud Cases","Legitimate Cases","Fraud Rate","Missing Values"),
  Value  = c(
    format(nrow(df), big.mark=","),
    format(sum(df$Class==1), big.mark=","),
    format(sum(df$Class==0), big.mark=","),
    paste0(round(mean(df$Class==1)*100,3), "%%"),
    as.character(sum(is.na(df)))
  )
)
kable(summary_df, col.names=c("Metric","Value")) %%>%%
  kable_styling(bootstrap_options=c("striped","hover","condensed"), full_width=FALSE)
```

## Class Distribution

```{r}
class_df <- df %%>%% group_by(Class) %%>%%
  summarise(Count=n()) %%>%%
  mutate(Label=ifelse(Class==1,"Fraud","Legitimate"), Pct=round(Count/sum(Count)*100,3))

ggplot(class_df, aes(x=Label, y=Count, fill=Label)) +
  geom_bar(stat="identity", width=0.5) +
  geom_text(aes(label=paste0(Count,"\\n(",Pct,"%%)")), vjust=-0.2, size=4) +
  scale_fill_manual(values=c("Fraud"="#e74c3c","Legitimate"="#27ae60")) +
  scale_y_continuous(labels=comma) +
  labs(title="Class Distribution", x=NULL, y="Count") +
  theme_minimal(base_size=13) + theme(legend.position="none")
```

## Transaction Amount

```{r}
df_amt <- df[df$Amount < 2000,]
ggplot(df_amt, aes(x=Amount, fill=Class)) +
  geom_histogram(bins=60, alpha=0.7, position="identity") +
  scale_fill_manual(values=c("0"="#27ae60","1"="#e74c3c"),labels=c("0"="Legit","1"="Fraud")) +
  scale_x_continuous(labels=dollar) +
  labs(title="Amount Distribution (< $2000)", x="Amount", y="Count", fill=NULL) +
  theme_minimal(base_size=13)
```

## Transaction Time

```{r}
df$Hour <- df$Time / 3600
ggplot(df, aes(x=Hour, fill=Class)) +
  geom_histogram(bins=48, alpha=0.7, position="identity") +
  scale_fill_manual(values=c("0"="#3498db","1"="#e74c3c"),labels=c("0"="Legit","1"="Fraud")) +
  labs(title="Transactions by Hour", x="Hour", y="Count", fill=NULL) +
  theme_minimal(base_size=13)
```

## Statistical Summary

```{r}
fraud_df <- df[df$Class==1,]
legit_df <- df[df$Class==0,]

stats_df <- data.frame(
  Metric     = c("Mean Amount","Median Amount","Max Amount","Std Amount"),
  Legitimate = c(
    dollar(round(mean(legit_df$Amount),2)),
    dollar(round(median(legit_df$Amount),2)),
    dollar(round(max(legit_df$Amount),2)),
    dollar(round(sd(legit_df$Amount),2))
  ),
  Fraud = c(
    dollar(round(mean(fraud_df$Amount),2)),
    dollar(round(median(fraud_df$Amount),2)),
    dollar(round(max(fraud_df$Amount),2)),
    dollar(round(sd(fraud_df$Amount),2))
  )
)
kable(stats_df) %%>%%
  kable_styling(bootstrap_options=c("striped","hover"), full_width=FALSE)
```

---
*Generated by FraudGuard R Analysis Module*
', csv_path)

# Fix %% back to % for R markdown
rmd_content <- gsub("%%%%", "%%", rmd_content)

rmd_path <- file.path("r_output", "fraud_report.Rmd")
out_dir  <- "r_output"
dir.create(out_dir, showWarnings = FALSE)
writeLines(rmd_content, rmd_path)

cat("Rendering R Markdown report...\n")
tryCatch({
  rmarkdown::render(
    input       = rmd_path,
    output_file = "fraud_report.html",
    output_dir  = out_dir,
    quiet       = FALSE
  )
  report_html <- file.path(out_dir, "fraud_report.html")
  if (!file.exists(report_html)) {
    stop("Render finished but fraud_report.html was not created.")
  }
  cat("=== Report saved to: r_output/fraud_report.html ===\n")
}, error = function(e) {
  cat("Render error:", conditionMessage(e), "\n")
  cat("Tip: Make sure pandoc is installed. Run: https://pandoc.org/installing.html\n")
  quit(status = 1)
})
